name: Unity Build (Android)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unity - Build APK
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2023.2.1f1
          targetPlatform: Android
          buildMethod: Plugins.CI.Editor.Builder.BuildAndroidAPK_Dev
          projectPath: .
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: build/**/*.apk
