name: Unity Build on

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Setup Unity
        uses: buildalon/activate-unity-license@v1
        with:
          license: 'Personal'
          username: '${{ secrets.UNITY_USERNAME }}'
          password: '${{ secrets.UNITY_PASSWORD }}'

      - name: Build Android
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.21f1
          targetPlatform: Android
          buildPath: Artifacts/Android

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AndroidBuild
          path: Artifacts
