name: Unity Build with Cake (Android)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/sinlessdevil/unity-ci-image:2023.2.1f1

    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_PATH: /opt/unity/Unity/Editor/Unity

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build APK with Unity CLI
        run: |
          ${UNITY_PATH} \
            -batchmode \
            -nographics \
            -silent-crashes \
            -logFile /dev/stdout \
            -projectPath . \
            -executeMethod Plugins.CI.Editor.Builder.BuildAndroidAPK_Dev \
            -quit

      - name: Build project with Cake (build, tests, logs)
        run: |
          dotnet tool restore
          dotnet cake build.cake --target=Run-CI-Pipeline

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: artifacts/*.apk
