name: Unity Build with Cake (Android)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/sinlessdevil/unity-ci-image:2023.2.1f1
      credentials:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.CR_PAT }}

    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 💾 Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: ✅ Activate Unity License (Personal)
        run: |
          echo "🧾 Accepting license and activating Unity..."
          echo "Y" | /opt/unity/Unity/Unity \
            -batchmode -nographics -quit \
            -username "$UNITY_EMAIL" \
            -password "$UNITY_PASSWORD" \
            -logFile /root/activation.log || echo "❌ Activation failed"

          echo "------ ACTIVATION LOG ------"
          cat /root/activation.log || echo "❌ No activation log found"

      - name: 🛠️ Build APK via Unity Method
        run: |
          echo "🔧 Starting Unity build..."
          /opt/unity/Unity/Unity \
            -batchmode -nographics \
            -quit \
            -projectPath . \
            -executeMethod Plugins.CI.Editor.Builder.BuildAndroidAPK_Dev \
            -logFile /root/unity.log || echo "❌ Unity crashed"

          echo "------ UNITY LOG ------"
          cat /root/unity.log || echo "❌ Unity log not found"

      - name: 🧪 Run Cake pipeline (tests, logs)
        run: |
          dotnet tool restore
          dotnet cake build.cake --target=Run-CI-Pipeline

      - name: 📤 Upload APK Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: artifacts/*.apk
