name: CI Cake Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Install Dependencies
        run: sudo apt-get install -y unzip

      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          unityVersion: 2023.2.1f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Set Unity Editor Path
        run: echo "UNITY_EDITOR_PATH=/opt/unity/editor" >> $GITHUB_ENV

      - name: Check Unity Path
        run: |
          echo "Checking if Unity exists at $UNITY_EDITOR_PATH/Unity"
          ls -la $UNITY_EDITOR_PATH

      - name: Build APK (Unity)
        run: |
          echo "Using Unity at $UNITY_EDITOR_PATH"
          $UNITY_EDITOR_PATH/Unity \
            -batchmode \
            -nographics \
            -quit \
            -projectPath . \
            -executeMethod Plugins.CI.Editor.Builder.BuildAndroidAPK_Dev \
            -logFile artifacts/unity.log

      - name: Run Cake Build (Post-processing, uploads etc)
        run: dotnet cake build.cake --target=Build-All

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: artifacts/*.apk
          