name: Unity Build with Cake (Android)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/sinlessdevil/unity-ci-image:2023.2.1f1
      credentials:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.CR_PAT }}

    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 💾 Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: 🔑 Decode Unity License
        run: |
          mkdir -p /root/.local/share/unity3d/Unity
          echo "$UNITY_LICENSE" | base64 -d > /root/.local/share/unity3d/Unity/Unity_lic.ulf

      - name: 🛠️ Build APK via Unity Method
        run: |
          echo "Checking Unity executable:"
          ls -la /opt/unity/Unity/Unity || echo "❌ Unity binary not found!"

          echo "Checking license file:"
          ls -la /root/.local/share/unity3d/Unity/Unity_lic.ulf || echo "❌ License not found!"

          echo "🔧 Starting Unity build..."
          /opt/unity/Unity/Unity \
           -batchmode -nographics \
           -manualLicenseFile /root/.local/share/unity3d/Unity/Unity_lic.ulf \
           -quit \
           -logFile - \
           -projectPath . \
           -executeMethod Plugins.CI.Editor.Builder.BuildAndroidAPK_Dev

      - name: 🧪 Run Cake pipeline (tests, logs)
        run: |
          dotnet tool restore
          dotnet cake build.cake --target=Run-CI-Pipeline

      - name: 📤 Upload APK Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: artifacts/*.apk
