name: Unity Build with Cake (Android)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Setup Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2023.2.1f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project with Cake
        run: |
          dotnet tool restore
          dotnet cake build.cake --target=Build-All
        env:
          UNITY_PATH: /opt/unity/editor/Unity
          BUILD_METHOD: Plugins.CI.Editor.Builder.BuildAndroidAPK_Dev
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: artifacts/*.apk
