name: CI Cake Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: ubuntu-latest

    env:
      UNITY_PATH: /opt/unity/editor/Unity

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Setup Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2023.2.1f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Run Cake Build
        run: dotnet cake build.cake --target=Build-All

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: artifacts/**/*.apk
