name: CI Cake Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Install Dependencies
        run: sudo apt-get install -y unzip

      - name: Run Cake Build
        run: dotnet cake build.cake --target=Build-All

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: artifacts/*.apk
